name: Build, publish and deploy project to Simply

on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish
        
      - name: Test with .NET
        run: dotnet test

      - name: Deploy to Simply        
        uses: talunzhang/auto-web-deploy@v1.0.1
        with:
          website-name: alviin21-001-site1
          server-computer-name: https://win8114.site4now.net:8172/msdeploy.axd?site=alviin21-001-site1
          server-username: alviin21-001
          server-password: Alviin21
          source-path: '\root\home\alviin21-001\www\site1\'
      - name: Migrate
        run: |
         dotnet tool install --global dotnet-ef
         dotnet ef database update --connection "<Data Source=SQL8020.site4now.net;Initial Catalog=db_aac121_alviin21;User Id=db_aac121_alviin21_admin;Password=Alviin21>"
